//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIF.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is the incorrect size..
        /// </summary>
        internal static string ArgumentBadSize {
            get {
                return ResourceManager.GetString("ArgumentBadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column length must be greater than zero..
        /// </summary>
        internal static string ArgumentColumnLength {
            get {
                return ResourceManager.GetString("ArgumentColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column specified is invalid..
        /// </summary>
        internal static string ArgumentInvalidColumn {
            get {
                return ResourceManager.GetString("ArgumentInvalidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row specified is invalid..
        /// </summary>
        internal static string ArgumentInvalidRow {
            get {
                return ResourceManager.GetString("ArgumentInvalidRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified matrices are incompatible for this operation..
        /// </summary>
        internal static string ArgumentMatricesIncompatible {
            get {
                return ResourceManager.GetString("ArgumentMatricesIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thie matrix is not a column vector..
        /// </summary>
        internal static string ArgumentMatrixisNotColumnVector {
            get {
                return ResourceManager.GetString("ArgumentMatrixisNotColumnVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thie matrix is not a row vector..
        /// </summary>
        internal static string ArgumentMatrixisNotRowVector {
            get {
                return ResourceManager.GetString("ArgumentMatrixisNotRowVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thie matrix is not a vector..
        /// </summary>
        internal static string ArgumentMatrixIsNotVector {
            get {
                return ResourceManager.GetString("ArgumentMatrixIsNotVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row length must be greater than zero..
        /// </summary>
        internal static string ArgumentRowLength {
            get {
                return ResourceManager.GetString("ArgumentRowLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified size must be greater than zero..
        /// </summary>
        internal static string ArgumentSizeZero {
            get {
                return ResourceManager.GetString("ArgumentSizeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start column must be less than the end column..
        /// </summary>
        internal static string ArgumentStartColumnGreaterThanEndRow {
            get {
                return ResourceManager.GetString("ArgumentStartColumnGreaterThanEndRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start row must be less than the end row..
        /// </summary>
        internal static string ArgumentStartRowGreaterThanEndRow {
            get {
                return ResourceManager.GetString("ArgumentStartRowGreaterThanEndRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector supplied does not match the row and column count..
        /// </summary>
        internal static string ArgumentVectorNotValid {
            get {
                return ResourceManager.GetString("ArgumentVectorNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network has not been trained..
        /// </summary>
        internal static string NetworkNotTrained {
            get {
                return ResourceManager.GetString("NetworkNotTrained", resourceCulture);
            }
        }
    }
}
